### ISSUE TITLE
Typo in LabscriptError of PrawnBlaster

### ISSUE THREAD

**Issue by rpanderson** [labscript-suite/labscript-devices#77]
The new `PrawnBlaster` device class has multiple clocklines that are auto-generated. These form an attribute `clocklines` of the device instance, but the attribute is referred to as `clockline` in the `LabscriptError` strings:

https://github.com/labscript-suite/labscript-devices/blob/7c1c48597be3eab72fd1d960575b7e412b41b709/labscript_devices/PrawnBlaster/labscript_devices.py#L40

https://github.com/labscript-suite/labscript-devices/blob/7c1c48597be3eab72fd1d960575b7e412b41b709/labscript_devices/PrawnBlaster/labscript_devices.py#L45

**Comment by philipstarkey** [comment]
Thanks Russ. Fixed in e7b3571
